/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#271900",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "on-error-container": "#93000a",
        "primary": "#00342b",
        "on-tertiary-container": "#b2b1b1",
        "error": "#ba1a1a",
        "outline": "#707975",
        "on-surface-variant": "#3f4945",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-primary-fixed": "#00201a",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-bright": "#fbf9f9",
        "tertiary-fixed": "#e3e2e2",
        "secondary-fixed": "#ffdea6",
        "surface-tint": "#29695b",
        "inverse-primary": "#94d3c1",
        "surface-container-high": "#e9e8e7",
        "on-primary-fixed-variant": "#065043",
        "on-secondary-fixed-variant": "#5d4200",
        "inverse-on-surface": "#f2f0f0",
        "background": "#fbf9f9",
        "on-tertiary-fixed-variant": "#464747",
        "inverse-surface": "#303031",
        "error-container": "#ffdad6",
        "secondary-container": "#fdc34d",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#94d3c1",
        "on-primary-container": "#7ebdac",
        "primary-fixed": "#afefdd",
        "on-background": "#1b1c1c",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bfc9c4",
        "primary-container": "#004d40",
        "tertiary-container": "#434444",
        "surface-container-highest": "#e3e2e2",
        "tertiary": "#2d2e2e",
        "surface": "#fbf9f9",
        "surface-dim": "#dbdad9",
        "on-surface": "#1b1c1c",
        "on-primary": "#ffffff",
        "on-secondary-container": "#715000",
        "surface-container": "#efeded",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#f7bd48",
        "secondary": "#7b5800",
        "surface-variant": "#e3e2e2"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
